server:
  port: 8081

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: msg-producer

spring:
  application:
    name: rocketmq-producer
  datasource:
    url: jdbc:mysql://localhost:3306/shane
    username: root
    password: mysql2023
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: org.shane.entity