server:
  port: 8082

spring:
  application:
    name: dubbo-consumer

dubbo:
  application:
    name: dubbo-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://106.14.216.125:2181